spring:
  datasource:
    hikari:
      connection-test-query: SELECT 1
      minimum-idle: 1
      maximum-pool-size: 5
      pool-name: dbcp1
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/house?autoReconnect=true&useSSL=false
    username: postgres
    password: 123456
    type: com.zaxxer.hikari.HikariDataSource

############################# Redis config #############################
cache:
  # pool config
  pool:
    maxIdle: 15
    maxTotal: 30
    maxWaitMillis: 6000
    minIdle: 1
    numTestsPerEvictionRun: 10
    testOnBorrow: true
    testOnReturn: true
    testWhileIdle: true
    timeBetweenEvictionRunsMillis: 6000
  # enable redis
  redis:
    enabled: true
redis:
  database: 0
  host:
    address: localhost
    password:
    port: 6379
  setup:
    flushdb: true

ribbon:
  ReadTimeout: 10000

hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: THREAD
          thread:
            timeoutInMilliseconds: 10000

